### ISSUE TITLE
Whitelisting IP addresses

### ISSUE THREAD

**Issue by gribachev** [envoyproxy/ratelimit#122]
Hi,
We are trying to setup ratelimit for our services and can't seem to be able to overcome 1 issue, we can't seem to be able to whitelist our IP addresses in config file.

`---
domain: webback

descriptors:

  - key: generic_key
    value: registration_service_stage0
    descriptors:
      - key: remote_address
        rate_limit:
          unit: hour
          requests_per_unit: 16

  - key: generic_key
    value: registration_service_stage1
    descriptors:
      - key: remote_address
        rate_limit:
          unit: minute
          requests_per_unit: 4

  - key: generic_key
    value: registration_service_stage2
    descriptors:
      - key: remote_address
        rate_limit:
          unit: second
          requests_per_unit: 2

  - key: generic_key
    value: forgot_password_stage_0
    descriptors:
      - key: remote_address
        rate_limit:
          unit: hour
          requests_per_unit: 12

  - key: generic_key
    value: forgot_password_stage_1
    descriptors:
      - key: remote_address
        rate_limit:
          unit: minute
          requests_per_unit: 1

`
Could you please maybe give us an idea on how we can go around our problem?
Thanks.

**Comment by teamfighter** [comment]
Subscribed

**Comment by ysawa0** [comment]
I think something like this would work
```
descriptors:
  - key: generic_key
    value: registration_service_stage0
    descriptors:
        - key: remote_address
          value: 1.1.1.1
        - key: remote_address
          rate_limit:
            unit: hour
            requests_per_unit: 16
```
ratelimit service would first match against the value of `1.1.1.1`, if it matches then it would allow the request. Otherwise, give it a threshold of 16/hour.
