### ISSUE TITLE
Redis cluster mode support

### ISSUE THREAD

**Issue by Taiters** [envoyproxy/ratelimit#125]
Hey,

I'd like to add support for Redis running in [cluster mode](https://redis.io/topics/cluster-spec).

The existing redis client, [radix.v2](https://github.com/mediocregopher/radix.v2) has a [cluster](https://godoc.org/github.com/mediocregopher/radix.v2/cluster) package which supports this, so this change would involve pulling that package, updating the driver impl, and potentially exposing a new config value to allow the user to specify whether or not they're running Redis as a cluster.

Happy to open a PR for this if it's something you would like added.

**Comment by mattklein123** [comment]
Sure SGTM!

**Comment by Taiters** [comment]
Perfect, feel free to assign to me 👍

**Comment by ysawa0** [comment]
Tacking onto this issue: I'm currently running Ratelimit service as Pods in k8s and running an Envoy sidecar along side each; I'm having Redis requests routed by the Clustered Redis client in Envoy as we are using ElastiCache Redis in Cluster mode as the backend.

I'm seeing p99.9 ratelimit to Redis latency spiking to 25ms+ 
vs just self-hosting some Redis pods and using the Envoy redis_proxy (no clustered client) to route, which is much more stable latency wise.

How is Lyft provisioning their Redis? I'd like to keep p999 latency for ratelimit service and amount of fail-opens as low as possilbe. Thanks for any help!

**Comment by Jiaweizdev** [comment]
Hi, I just wanted to check if there is any progress on this issue?

**Comment by wwillsey** [comment]
+1 for the question by @ysawa0. I have concerns over availability of the single redis host compared to a cluster. @mattklein123 Do you think you could shed any light on the suggested redis configuration? 

@ysawa0 are you using the redis cluster support as described in the [envoy docs](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_protocols/redis#redis-cluster-support-experimental)? Im interested in supporting the rate limit service via a redis cluster, and would like to better understand the implications of doing so. 

I've opened a conversation in the Envoy-Users group if thats a better place to discuss: https://groups.google.com/g/envoy-users/c/tj_Kzh6F9JY

**Comment by mattklein123** [comment]
At Lyft we used to use basic Envoy redis proxy support for outbound connections. Now, we use Envoy's redis cluster support AFAIK. We definitely don't use a single redis backend for the ratelimit service. Really, whatever mechanism you normally use to scale out Redis should work here.

**Comment by caitong93** [comment]
Envoy redis cluster configuration example, hope it helps

```
static_resources:
  listeners:
  - name: redis_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 1999
    filter_chains:
    - filters:
      - name: envoy.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.redis_proxy.v2.RedisProxy
          stat_prefix: egress_redis
          settings:
            op_timeout: 5s
            enable_redirection: true
            enable_hashtagging: true
          prefix_routes:
            catch_all_route:
              cluster: redis_cluster
          downstream_auth_password:
            inline_string: "123456"
  clusters:
  - name: redis_cluster
    typed_extension_protocol_options:
      envoy.redis_proxy:
        '@type': type.googleapis.com/envoy.config.filter.network.redis_proxy.v2.RedisProtocolOptions
        auth_password:
          inline_string: "123456"
    connect_timeout: 1s
    dns_lookup_family: V4_ONLY
    lb_policy: CLUSTER_PROVIDED
    load_assignment:
      cluster_name: redis_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: node1.redis-cluster
                port_value: 6379
        - endpoint:
            address:
              socket_address:
                address: node2.redis-cluster
                port_value: 6379
        - endpoint:
            address:
              socket_address:
                address: node3.redis-cluster
                port_value: 6379
    cluster_type:
      name: envoy.clusters.redis
      typed_config:
        "@type": type.googleapis.com/google.protobuf.Struct
        value:
          cluster_refresh_rate: 10s
          cluster_refresh_timeout: 2s
          redirect_refresh_interval: 1s
          redirect_refresh_threshold: 10
```
