### ISSUE TITLE
Proposal: Support header value for use as Rate limit tokens 

### ISSUE THREAD

**Issue by wwillsey** [envoyproxy/ratelimit#167]
This proposal is to allow use of a configurable descriptor that can pull a value to use as the rate limit tokens to consume for a given request, rather than only rate-limiting based on _number_ of requests per unit of time. 

Example:
```
request with header 'Rate-Limit-Tokens'=5
```
Example descriptor config
```
domain: example
descriptors:
  - key: key
    value: value
    rate_limit:
      tokens_per_unit: 50
      rate_limit_token_header: 'Rate-Limit-Tokens'
      unit: second
```

In this case, only 10 requests per second would be allowed of the example request.
