### ISSUE TITLE
Way to create different time units?

### ISSUE THREAD

**Issue by vincentjames501** [envoyproxy/ratelimit#190]
We'd like to implement rate limiting such that certain time-periods have time have different limits (i.e. bursting). For example:

Scenario | Time-period (sec) | Max allowed operations
-- | -- | --
Send to Conversation | 1 | 5
Send to Conversation | 30 | 60
Send to Conversation | 300 | 100

Right now the configuration is pretty simple with:

```yaml
rate_limit:
  unit: <second, minute, hour, day>
  requests_per_unit: <uint>
```

The problem is that I can't adjust the unit to be something like `30 seconds` or `5 minutes` (or at least I'm not clear how one would set that).

What would folks think about adding some unit multiplier such as:

```yaml
rate_limit:
  unit_multiplier: <uint | default=1>
  unit: <second, minute, hour, day>
  requests_per_unit: <uint>
```

This would allow someone to easily express `30 seconds` or `5 minutes`?

**Comment by vincentjames501** [comment]
It also appears I can only get one rate limit to match and be processed. Is there a way to have multiple rate limits be applied to a single route?

```yaml
                      routes:
                        - match:
                            prefix: /api/
                            headers: 
                              name: :method
                              exact_match: GET
                          route:
                            cluster: api
                            rate_limits:
                              - actions:
                                  - request_headers:
                                      header_name: x-user-id
                                      descriptor_key: default_get_limit_sm
                                  - request_headers:
                                      header_name: x-user-id
                                      descriptor_key: default_get_limit_med
                                  - request_headers:
                                      header_name: x-user-id
                                      descriptor_key: default_get_limit_lg
```

```
---
domain: rl
descriptors:
  - key: default_get_limit_sm
    rate_limit:
      unit: second
      requests_per_unit: 30
  - key: default_get_limit_md
    rate_limit:
      unit: minute
      requests_per_unit: 120
  - key: default_get_limit_lg
    rate_limit:
      unit: hour
      requests_per_unit: 1800
```

It could be neat if instead of `rate_limit` there was `rate_limits` which would be an array of `rate_limit` objects?

**Comment by cesutherland** [comment]
We would also benefit from "bursting" where, eg. 30r/3s would support a burst of 30 requests with a sustained traffic of 10 requests/s

**Comment by vincentjames501** [comment]
Can this be tagged with help wanted at least?

**Comment by mattklein123** [comment]
Sorry what is the actual request? I think we support multiple limits today. Can bursting be expressed as multiple concurrent rate limits?

**Comment by vincentjames501** [comment]
@mattklein123 Yes, this service can represent multiple rate limits for bursting today. The issue is our company has different time windows they want to enforce limits on that don't fit into second, minute, hour, and day units. For example, you can't really make these limits:

```
X requests over 30 seconds
X requests over 5 minutes
X requests over 30 minutes
X requests over 12 hours
X requests over 7 days
```

The proposal I made earlier was some sort of unit multiplier such as:

```yaml
rate_limit:
  unit_multiplier: <uint | default=1>
  unit: <second, minute, hour, day>
  requests_per_unit: <uint>
```

which would allow you to represent any time period. Does that make sense?

**Comment by mattklein123** [comment]
> which would allow you to represent any time period. Does that make sense?

Yup OK makes sense. I will mark it help wanted.

**Comment by MischaWeerwag** [comment]
I would also like to set multiple units for a single action so:
```
            descriptors:
              - key: remote_address
                rate_limit:
                  unit: second
                  requests_per_unit: 3
                rate_limit:
                  unit: day
                  requests_per_unit: 100
```
That is currently (afaik) not possible without duplicating the complete action with a generic key.
