### ISSUE TITLE
envconfig cannot convert REDIS_PIPELINE_WINDOW to time duration

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [envoyproxy/ratelimit#199]
we find this error when configuring `REDIS_PIPELINE_WINDOW`:
```
panic: envconfig.Process: assigning _REDIS_PIPELINE_WINDOW to REDIS_PIPELINE_WINDOW: converting '1' to type time.Duration

goroutine 1 [running]:
github.com/envoyproxy/ratelimit/src/settings.NewSettings(...)
	/ratelimit/src/settings/settings.go:55
github.com/envoyproxy/ratelimit/src/service_cmd/runner.(*Runner).Run(0xc000197f68)
	/ratelimit/src/service_cmd/runner/runner.go:39 +0x973
main.main()
	/ratelimit/src/service_cmd/main.go:7 +0x43
```

we have configmap and added the configmap as a variable in Kubernetes:
```
apiVersion: v1
data:
  LOCAL_CACHE_SIZE_IN_BYTES: "32767"
  LOG_LEVEL: info
  REDIS_PIPELINE_LIMIT: "1"
  REDIS_PIPELINE_WINDOW: "1"
  REDIS_POOL_SIZE: "40"
  REDIS_TYPE: cluster
  REDIS_URL: redis-cluster-1:6379, redis-cluster-2:6379, redis-cluster-3:6379
  STATSD_HOST: statsd-exporter.infrastructure.svc
  USE_STATSD: "true"
kind: ConfigMap
metadata:
  name: rate-limit-env
---
    envFrom:
    - configMapRef:
        name: rate-limit-env
```
