### ISSUE TITLE
Proposal: Add explicit unlimited rate limits

### ISSUE THREAD

**Issue by thao-wish** [envoyproxy/ratelimit#241]
Currently we can achieve implicit unlimited rate limits by not specifying a rate limit in the configuration. However, we'll lose the metrics (total_hits, within_limits) for those rate limits. The proposal is to add an explicit unlimited rate limit. An example config file could look like this:
```
domain: mongo_cps
descriptors:
  - key: database
    value: users
    rate_limit:
      unit: second
      requests_per_unit: unlimited
```
We can skip the trip to redis/memcached if unlimited rate limits are requested. Please let me know if the team is open to this request or discuss any alternatives. The main concern is to be able to get the metrics for the unlimited rate limits.
