### ISSUE TITLE
[Question] Is it possible to apply multiple limits to the same descriptor

### ISSUE THREAD

**Issue by tomasbasham** [envoyproxy/ratelimit#262]
I have this use case where I want to specify a rate limit for a given descriptor based on two units of time. Specifically I'm after the ability to specify:
- A daily rate limit, and
- A burst limit

For example I have been trying to implement the following:

```yaml
domain: mydomain
descriptors:
- key: package
  value: free
  descriptors:
  - key: account_id
    rate_limit:
      unit: second
      requests_per_unit: 10
  - key: account_id
    rate_limit:
      unit: day
      requests_per_unit: 250
- key: package
  value: paid
  descriptors:
  - key: account_id
    rate_limit:
      unit: second
      requests_per_unit: 20
  - key: account_id
    rate_limit:
      unit: day
      requests_per_unit: 1000
```
This is not allowed since you cannot have the same (key/value) being used at the same descriptor level, but my original assumption was that this configuration would return a 429 if a request caused any of the limits (`account_id` descriptors) to be met. Is there some configuration to make this possible?
