### ISSUE TITLE
RFC: an approach for a descriptor to replace descriptors in a different format

### ISSUE THREAD

**Issue by dweitzman** [envoyproxy/ratelimit#280]
The matching of request descriptors to configured limits today is always an OR that pulls together any matching limit configurations.

This makes it easy to _reduce_ quota for specific edge cases (like a misbehaving client), but sometimes difficult to _increase_ quota.

Here's a sketch of a config where one rate limit is able to override a different rate limit with the help two additional properties on "rate_limit": "name" and "replaces"

Thoughts?

```
# Typically a client has 200qpm quota that they can freely
# distribute across any of assorted insert/update/delete endpoints
- key: endpoint_group
  value: write_endpoints
  descriptors:
  - key: client_id
    rate_limit:
      name: "write_endpoint_limit" # This "name" can be referred to by the other rate limit pattern below
      requests_per_unit: 200
      unit: minutes

# Client 1234 has independent, higher quota for insert_foo_endpoint,
# and also still has 200qpm quota to spread across other write endpoints
# like "update_bar_endpoint" or "delete_bazz_endpoint"
- key: endpoint_name
  value: insert_foo_endpoint
  descriptors:
  - key: client_id
    value: 1234 # "foo" client gets increased/separate quota, but only for "insert_foo_endpoint"
                # Their "update_bar_endpoint" and "delete_bazz_endpoint" queries still come from the 200qpm
                # default "write_endpont_limit" quota
    rate_limit:
      # This "replaces" causes any other limit with a matching name
      # to be dropped during constructLimitsToCheck() in src /service/ratelimit.go
      replaces:
      - "write_endpoint_limit"
      requests_per_unit: 400
      unit: minute
```
