### ISSUE TITLE
Multiple tiered descriptors with the same top tier value. 

### ISSUE THREAD

**Issue by mhelkey** [envoyproxy/ratelimit#287]
Hello,

I have a set of descriptors where multiple of the top tier descriptors have the same value, and the rate limit service does not go beyond the top tier until there is a more specific match. 

For example, I have two rate limits

```yaml
descriptors:
    - key: generic_key
      value: abc
      descriptors:
        - key: PATH
          rate_limit:
            unit: minute
            requests_per_unit: 3
    - key: generic_key
      value: abc
      descriptors:
        - key: PATH
          value: "/foo"
          rate_limit:
            unit: minute
            requests_per_unit: 100
```

When I do nested rules like this, the rate limit service only looks at the top key-value pair to determine if there are duplicates, like so
`error loading new configuration from runtime: config.yaml: duplicate descriptor composite key 'domain.generic_key_abc'`

Is there a way that I could get the loading to look at the entire nested rule set before it determines that two separate rules are duplicates? Because the two rules that I have in my config file are not identical, but because they have the same top level key-value pair, the service thinks that they are identical.

**Comment by ysawa0** [comment]
you can simply combine them eg:
```
descriptors:
    - key: generic_key
      value: abc
      descriptors:
        - key: PATH
          value: "/foo"
          rate_limit:
            unit: minute
            requests_per_unit: 100
        - key: PATH
          rate_limit:
            unit: minute
            requests_per_unit: 3
```
make sure to have `          value: "/foo"` on top so it matches first
