### ISSUE TITLE
Handling multi value descriptors

### ISSUE THREAD

**Issue by santhosh5050309** [envoyproxy/ratelimit#300]
Want to implement ratelimiting per individual
```
descriptors:
    - key: cust
      value: A1
      rate_limit:
        requests_per_unit: 1
        unit: minute
    - key: cust
      value: A2
      rate_limit:
        requests_per_unit: 1
        unit: minute
    - key: cust
      value: A3
      rate_limit:
        requests_per_unit: 1
        unit: minute
```
here ratelimiting is done individually but data is repeated,can someone help me how to solve this data repeatition
below if i just put key as cust and value undefined then all the customers are ratelimited as a single individual
```
descriptors:
    - key: cust
      rate_limit:
        requests_per_unit: 1
        unit: minute
```
I WANT TO RATELIMIT PER CUSTOMER, is there any alternate way without repeating the key,values?
