### ISSUE TITLE
Connection to Redis broken with latest version of ratelimit service

### ISSUE THREAD

**Issue by aparna-kan** [envoyproxy/ratelimit#303]
Hi, 

I'm trying to use the ratelimit service independently without Istio or Envoy. Here is my configuration:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-limit-service
  namespace: rl
  labels:
    app: rate-limit-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rate-limit-service
  template:
    metadata:
      labels:
        app: rate-limit-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9102"
        prometheus.istio.io/merge-metrics: "false"
    spec:
      containers:
        - name: rate-limit-service
          image: envoyproxy/ratelimit:38bc1460
          imagePullPolicy: Always
          command: ["/bin/ratelimit"]
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 6070
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1
              memory: 1Gi
          env:
            - name: USE_STATSD
              value: "false"
            - name: STATSD_HOST
              value: "localhost"
            - name: STATSD_PORT
              value: "9125"
            - name: LOG_FORMAT
              value: "json"
            - name: LOG_LEVEL
              value: "debug"
            - name: REDIS_SOCKET_TYPE
              value: "tcp"
            - name: REDIS_URL
              value: "redis:6379"
            - name: REDIS_TLS
              value: "true"
            - name: REDIS_POOL_SIZE
              value: "5"
            - name: CACHE_KEY_PREFIX
              value: "rl-"
            - name: LOCAL_CACHE_SIZE_IN_BYTES # 25 MB local cache
              value: "26214400"              
            - name: RUNTIME_ROOT
              value: "/data"
            - name: RUNTIME_SUBDIRECTORY
              value: "runtime"
            - name: RUNTIME_WATCH_ROOT
              value: "false"
            - name: RUNTIME_IGNOREDOTFILES
              value: "true"
          volumeMounts:
            - name: ratelimit-config
              mountPath: /data/runtime/config
      volumes:
        - name: ratelimit-config
          configMap:
            name: ratelimit-config
```

Image with SHA: 38bc1460 checked-in a month ago is able to connect to Redis successfully. However, this is broken again in the later revisions including master.
Here is the error:
```
{"@message":"runtime: adding key=config.yaml value=domain: ratelimit\ndescriptors:\n  - key: PATH\n    value: \"/src-ip\"\n    rate_limit:\n      unit: second\n      requests_per_unit: 1\n  - key: remote_address\n    rate_limit:\n      requests_per_unit: 10\n      unit: second\n  - key: HOST\n    value: \"aks.danielstechblog.de\"\n    rate_limit:\n      unit: second\n      requests_per_unit: 5 uint=false","@timestamp":"2021-10-07T18:28:02.330299371Z","level":"debug"}
{"@message":"connecting to redis on master.rate-limit-poc.uxmv92.apse1.cache.amazonaws.com:6379 with pool size 5","@timestamp":"2021-10-07T18:28:02.330506856Z","level":"warning"}
{"@message":"Implicit pipelining enabled: false","@timestamp":"2021-10-07T18:28:02.330549636Z","level":"debug"}
panic: x509: certificate signed by unknown authority
 
goroutine 1 [running]:
github.com/envoyproxy/ratelimit/src/redis.checkError(...)
        /ratelimit/src/redis/driver_impl.go:51
github.com/envoyproxy/ratelimit/src/redis.NewClientImpl(0xce66a0, 0xc000326080, 0x1, 0x0, 0x0, 0xc000040072, 0x3, 0xa70f96, 0x6, 0xc00003c05a, ...)
        /ratelimit/src/redis/driver_impl.go:117 +0xc33
github.com/envoyproxy/ratelimit/src/redis.NewRateLimiterCacheImplFromSettings(0x0, 0x0, 0xa68f33, 0x7, 0x1f90, 0xa70624, 0x7, 0x1f91, 0xa718de, 0x7, ...)
        /ratelimit/src/redis/cache_impl.go:22 +0x154
github.com/envoyproxy/ratelimit/src/service_cmd/runner.createLimiter(0xce3800, 0xc0000f8790, 0x0, 0x0, 0xa68f33, 0x7, 0x1f90, 0xa70624, 0x7, 0x1f91, ...)
        /ratelimit/src/service_cmd/runner/runner.go:53 +0x27b
github.com/envoyproxy/ratelimit/src/service_cmd/runner.(*Runner).Run(0xc000464f00)
        /ratelimit/src/service_cmd/runner/runner.go:108 +0x416
main.main()
        /ratelimit/src/service_cmd/main.go:10 +0x16a
```

Please let me know if I'm missing something?
Also, the documentation says that hot reloading is supported, but this is not what I am seeing when testing (If I change only limits, the new values picked up, but any other change like new descriptors are not picked up). Am I missing something?
