### ISSUE TITLE
Feature request: regex on key's value

### ISSUE THREAD

**Issue by uykusuz** [envoyproxy/ratelimit#304]
Not sure if it's by design, so forgive me my question. I would love to express something like:

```yaml
descriptors:
  - key: path
    value: "/part1/.*"
```

What do you think about this?
