### ISSUE TITLE
Emitted metrics doesn't include key

### ISSUE THREAD

**Issue by jespersoderlund** [envoyproxy/ratelimit#311]
The rate limit metrics emitted doesn't include the key unless it's an configured as an explicit value, this makes the metrics a lot less useful for identifying the entity that has triggered the rate limit and take action.

For example with a rate limit config like this:

```
...
key: operation
ratelimit:
   unit: minutes
   value: 10
key: operation
value: opA
ratelimit:
   unit: minutes
   value: 20
key: operation
value: opB
ratelimit:
   unit: minutes
   value: 30
...
```
Metrics will only be emitted for keys:

`operation_opA`
`operation_opB`

Calls to operation opC and opD which relies on the base values are all grouped into the metric key

`operation`

Then it's not possible to distinguish them. The service is of course keeping a separate rate limit for them so they are not sharing, so it doesn't feel right to not emit metrics for them jointly.

So the proposal is to have a setting which would enable emitting the statistic also for the full key, or just emit it in parallel.

So the counter argument could be to list all the keys and while that might be possible, for some applications it would be a bit hard as the total number of entities can be quite large and be quite dynamic in nature.

Also another concern would be that it could lead to a lot of metrics being emitted, this could go hand-in-hand with another change to only emit over-limit and near-limit metrics + the total_metrics. I think it's rarely useful with the an individual metric for the successful rate limit calls. "Near" and "Over" should be enough to have details around
