### ISSUE TITLE
Use of wildcard in descriptor value

### ISSUE THREAD

**Issue by mcatany** [envoyproxy/ratelimit#317]
Hi,

We would like to use rate limit on header ":path"  for paths starting for example like: /api or /events

When we add a configuration like this:

```
- key: PATH
   value: /api/
   rate_limit:
       unit: minute
       requests_per_unit: 10

```
We notice that paths like "/api/feed" or "/api/whatever" are not included in the rule. Is there any way to set a wildcard  or similar to the descriptor value like: 

```
- key: PATH
   value: /api/*
   rate_limit:
       unit: minute
       requests_per_unit: 10

```
So all the paths under /api/.. go through the same rule?

Thanks

**Comment by ysawa0** [comment]
There's currently no way to use a wildcard in the key field

**Comment by alexclarkofficial** [comment]
Is there any interest in supporting this? I have a solution, I believe. https://github.com/alexclarkofficial/ratelimit/commit/5d0380a00a39ef64ecb77f901563bc5321795feb
If there's interest, I can finish this up and open a PR.

**Comment by matteoga** [comment]
it would be useful, i have a similar need and i'm currently using as workaround, a LUA filter to apply the regex and set a flag / key when the match happens, something like
```
configPatches:
    - applyTo: HTTP_FILTER
      match:
        # context omitted so that this applies to both sidecars and gateways
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value: # lua filter specification
          name: envoy.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |

              function envoy_on_request(request_handle)
                  path = request_handle:headers():get(":path")
                  apiPath = path:gsub('%/api(.*)', '')
                  metadata = request_handle:streamInfo():dynamicMetadata()
                  metadata:set("ratelimit", "apiPath", apiPath)
              end
```
and then use the metadata as descriptor

**Comment by CharlieC3** [comment]
Can this issue be reopened? It would be very helpful to my situation.

**Comment by m-rcl** [comment]
Given the information
```
- key: PATH
   value: /api/*
   rate_limit:
       unit: minute
       requests_per_unit: 10
```
> So all the paths under /api/.. go through the same rule?

I see two interpretations of a possible solution:
1. Calls to `/api/v2` should be blocked after 10 requests to `/api/v1`
2. `/api/v2`, `/api/v1` and `/api/v1/foo` should have 10 requests per minute each

To accomplish the former case, we use a custom action:
```
- actions:
  - header_value_match:
      descriptor_key: endpoint
      descriptor_value: api
      headers:
      - name: :path
        prefix_match: /api
```
Descriptor will match all calls to /api/* und this rule:
```
- key: endpoint
  value: api
   rate_limit:
       unit: minute
       requests_per_unit: 10
```

If I understand @alexclarkofficial's PR correctly, it targets the first option. In case the second option is needed, I could try elaborate a solution and open a PR.

**Comment by CharlieC3** [comment]
@m-rcl The custom action example you posted actually helped me out quite a bit without the ratelimit wildcard feature, thanks!

> So all the paths under /api/.. go through the same rule?

Based on this issue description, I would hazard a guess that the intended functionality is the first option you specified, where calls to `/api/v2` should be blocked after 10 requests to `/api/v1`.
It seems option 2 would still be very useful, but would implicitly be creating separate rules behind the scenes.

**Comment by alex-startengine** [comment]
We use wildcard descriptors to whitelist IPs given a certain CIDR range. We have used @alexclarkofficial 's solution to good effect.

**Comment by alex-startengine** [comment]
Re: [envoyproxy/ratelimit] Use of wildcard in descriptor value (Issue #317)

Your message has been received and will be reviewed by a Support
Specialist! Our team will get back to you as soon as possible, but please
account for a 48 business hour (2 business day) time period. We'll usually
get back within one business day but please keep in mind, during high peak
hours and filing season allow up to 48 business hours.

If you would like a pending campaign update to be approved, please email
***@***.**** and include your campaign name in the subject
line. ***@***.***>Our team will approve updates as soon as
possible, but please account for a 48 business hour (2 business day) review
period.

If you have questions about marketing, campaign updates, disbursements, or
amendments, we highly recommend reviewing our *Help Center*
<https://help.startengine.com/categories/for-companies-rJjXauRzK> as many
of the answers you are looking for should be covered in a help article*.*
<https://help.startengine.com/categories/for-companies-rJjXauRzK> Below are
some direct links to some of the directories:

*Dashboard Overview*
<https://help.startengine.com/en_us/dashboard-overview-ByrajWS1s> - *How to
access your Dashboard, An Overview of each Tab in the Dashboard*
*Marketing Help Center*
<https://help.startengine.com/categories/marketing-SkS9aOAfY>- *How do I
post "Updates" to my community? What can StartEngine do to market my raise?*
*Already Live Help Center*
<https://help.startengine.com/categories/already-live-SkVdpdRfF>- *How Do I
Withdraw Funds During my Reg CF Offering?, Reg CF Campaign Extension Policy*
*Templates Guide*
<https://drive.google.com/drive/folders/1YsH2nRg55fPgjfm4U7Izfvlrsay2pY4w?usp=sharing>-
*Templates to help with* *Organic Social, Landing Pages, Website Pop ups
strategies*
*StartEngine's Campaign Marketing Guide*
<https://startengine.notion.site/StartEngine-s-Campaign-Marketing-Guide-4a0128ab1b6d4fa4bafae30683567f47>-
*How Should I Approach My Campaign's Paid Media strategy?*

All requests are important to us, and our team is working diligently to
assure that all inquiries are responded to as quickly as possible. Please
note that we do work in chronological order, so sending multiple emails
will reset your original timestamp and likely cause further delays,
something none of us want!

If you still have not received a response within 72 business hours, please
check your spam/trash folders for any emails from ***@***.***
If we are not contacts in your email platform, our message could end up in
other folders that are not your main inbox.

We look forward to helping you!

- The StartEngine Team


On Fri, Mar 3, 2023 at 5:57 AM <
> ***@***.***> wrote:
>
>> Hey @alexclarkofficial I have use cases too in which your patch would
>> help a lot. Could you please create a PR out of it?
>>
> <www.facebook.com/StartEngineLA> <www.twitter.com/StartEngineLA>
<https://www.linkedin.com/company/startengined/mycompany/>
<www.instagram.com/StartEngineLA>

-- 


--

Know a founder or business looking for investors? Refer them to 
StartEngine and earn $4,000 cash: Refer Here 
<https://www.startengine.com/scout?utm_source=Referral&isource=referral-scout-email-signature>


*terms and conditions apply

StartEngine Crowdfunding is a not a 
broker-dealer, funding portal or investment adviser. StartEngine Capital, 
LLC is a funding portal registered with the US Securities and Exchange 
Commission (SEC) and a member of the Financial Industry Regulatory 
Authority (FINRA). StartEngine Primary, LLC is a broker-dealer and member 
of FINRA / SIPC. Neither StartEngine Crowdfunding nor StartEngine Capital 
is making any recommendation or giving any advice with respect to any 
company or offering discussed in this communication. To read our full 
disclosure, please visit this page - startengine dot com slash disclaimer.

**Comment by Pawka** [comment]
Since @alexclarkofficial is responding I've created a PR #403, fixed some tests and updated the `README.md`. Used original Alex' commit to keep the ownership. Please review my PR and let me know if any changes are needed. Thanks!

**Comment by CharlieC3** [comment]
I'm not sure this is working as expected. For example, the following config does not work for me using the latest commit:

```
    domain: ratelimit
    descriptors:
      - key: app
        value: api*
        descriptors:
          - key: endpoint
            value: /v2*
            descriptors:
              - key: remote_address
                rate_limit:
                  name: api-v2-default
                  unit: minute
                  requests_per_unit: 10
```

In this example, the wildcard is detected in the top-level descriptor (app=api*), however it is not acknowledged in nested descriptors like (endpoint=/v2*) for some reason.
Even if the top-level descriptor is not using a wildcard, I cannot get nested descriptors to have their wildcards respected.

Can this issue please be reopened? Or should a new one be created?
