### ISSUE TITLE
High RPS configuration setting recommendations?

### ISSUE THREAD

**Issue by JRemitz** [envoyproxy/ratelimit#322]
I know the recommendations are unique to the use cases, but I'm curious if there are any general recommendations for configuration settings for sites with high RPS?  My setup looks like this:

1. Envoy edge proxy setup in Kubernetes, reverse proxy to an upstream server
2. Ratelimit service deployed in Kubernetes. Single pod with Redis cluster.

When I test with higher RPS (600-1000+) I start to get `RLSE` errors in my access logs, responding with a `500`.  That's okay, I know I can flip `failure_mode_deny: false` but I don't want to allow the requests to go upstream.  If the rate limit service is overwhelmed, I'm okay with higher latency with retries, or finding a way to increase throughput with more resources.  Do I have any options here?  Also, I can't seem to find a "smoking gun" on where the bottleneck is, so any guidance for debug logging either in Envoy or Ratelimit would be much appreciated.  Thanks in advance!

**Envoy config**
```yaml
...
              http_filters:
              - name: envoy.ratelimit
                typed_config:
                  "@type": "type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit"
                  domain: test_domain
                  rate_limit_service:
                    transport_api_version: "v3"
                    grpc_service:
                      envoy_grpc:
                        cluster_name: ratelimit_service
                      timeout: 5s
                  failure_mode_deny: true
...
      - name: ratelimit_service
        connect_timeout: 5s
        type: STRICT_DNS
        dns_lookup_family: V4_ONLY
        lb_policy: ROUND_ROBIN
        protocol_selection: USE_CONFIGURED_PROTOCOL
        http2_protocol_options: {}
        load_assignment:
          cluster_name: ratelimit_service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: ratelimit-ratelimit-service
                    port_value: 8081
```

**Ratelimit Configs (mapped to env vars)**
```yaml
localCacheSizeBytes: 32767
grpcMaxConnectionAge: "86400s"
grpcMaxConnectionAgeGrace: "3600s"
useStatsD: "true"
statsDProtocol: "udp"
statsDPort: 8125
debugHost: "0.0.0.0"
debugPort: 6070
logFormat: "json"
logLevel: "debug"
redisSocketType: "tcp"
redisType: "CLUSTER" #"SINGLE"
redisPoolSize: 50
redisURL: "ratelimit-redis-cluster:6379"
redisPipelineWindow: 0 # 0.01s
redisPipelineLimit: 3
runtimeRootPath: "/data"
runtimeSubdirectory: "ratelimit"
runtimeWatchRoot: "false"
runtimeIgnoreDotFiles: "true"
```

**EDIT - Update:**
Okay, some updates. Turns out lowering RPS and I'm still getting these at a lower rate than I thought. As low as 100rps, give or take.

I enabled Envoy's debug logger with `-l debug` and sifting through the logs I found the culprit:
```sh
'grpc-status', '14'
'grpc-message', 'upstream request timeout'
```
Still digging.

**Comment by JRemitz** [comment]
While I can't explain the latency increase, I did [finally figure out](https://github.com/envoyproxy/envoy/issues/20070#issuecomment-1048025472) the timeout setting that was causing this to crash. The short of it is that this is configured in the Envoy `http_filter` for ratelimit.  There are **many** timeout settings that you can set. In all of the examples I've seen and tuning that I've read, it has focused on the `grpc_service.timeout` setting. However, there is a timeout in the parent of the `rate_limit_service` at the `ratelimit` filter that needed to be set. My Envoy config snippet for the http_filter looks like this now:

```yaml
              http_filters:
              - name: envoy.ratelimit
                typed_config:
                  "@type": "type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit"
                  domain: api_lookups
                  timeout: 5s
                  rate_limit_service:
                    transport_api_version: "v3"
                    grpc_service:
                      envoy_grpc:
                        cluster_name: ratelimit_service
                      timeout: 5s
                  failure_mode_deny: true
```
