### ISSUE TITLE
RateLimit Service MissBehaviour

### ISSUE THREAD

**Issue by vk-98** [envoyproxy/ratelimit#333]
If this rate limit starts misbehaving, then does it have any effect on the request serving? 
I have done a POC, in which redis started throwing some errors, and due to this Instead of getting a response from the intended service, I am getting  500 status returned from rate limiting service. 
Is there any workaround/solution for this?

**Comment by vishwajitdandage-psl** [comment]
@vk-98 have you found any solution to this issue?
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit-svc
  namespace: istio-system
spec:
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            name: '*:80'
            route:
              action: ANY
      patch:
        operation: MERGE
        value:
          rate_limits:
            - actions:
                - request_headers:
                    descriptor_key: PATH
                    header_name: ':path'
  workloadSelector:
    labels:
      istio: ingressgateway
```
I am creating above filter by following https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/ documentation. If I delete this filter than I can access the product page. But with this filer I am getting 500 Internal Server Error. 
`curl -s "http://$GATEWAY_URL/productpage" -o /dev/null -w "%{http_code}\n"`
