### ISSUE TITLE
Feature request: Stop incrementing cache keys when overall status is over limited

### ISSUE THREAD

**Issue by renuka-fernando** [envoyproxy/ratelimit#348]
## Scenario

Let's say we have grouped routes
1.  Group: **Foo**
    1.  /foo/v1/hello-1
2.  Group: **Bar**
    1.  /bar/v1/hello-1
    2.  /bar/v1/hello-special

And we need to apply the following rate limits.
1.  Per group -> 10 req/min
2.  Special rate limit for the route `/bar/v1/hello-special` in group **Bar** -> 3 req/min

Let's say the client invokes `/bar/v1/hello-special` 3 times, the remaining quota for `/bar/v1/hello-1` should be 7 since both routes are belonged to group **Bar**. We can achieve this by adding two actions in the route `/bar/v1/hello-special` as follows.

### Proxy yaml

```yaml
- match:
    prefix: /foo/v1/hello-1
  route:
    cluster: mock
    rate_limits:
      - actions:
          - generic_key:
              descriptor_key: "group"
              descriptor_value: "foo"


- match:
    prefix: /bar/v1/hello-1
  route:
    cluster: mock
    rate_limits:
      - actions:
          - generic_key:
              descriptor_key: "group"
              descriptor_value: "bar"
- match:
    prefix: /bar/v1/hello-special
  route:
    cluster: mock
    rate_limits:
      - actions:
          - generic_key:
              descriptor_key: "group"
              descriptor_value: "bar"
      - actions:
          - generic_key:
              descriptor_key: "special-policy"
              descriptor_value: "3PerMin"
```

### Rate Limit Service Config Yaml

```yaml
descriptors:
  - key: group
    rate_limit:
      unit: minute
      requests_per_unit: 10
  - key: special-policy
    value: 3PerMin
    rate_limit:
      unit: minute
      requests_per_unit: 3
```

## Current Issue

Let's say the client invokes `/bar/v1/hello-special` 8 times within 1min. So it gets
  - 200 OK - 3 times
  - 429 Too Many Requests - 5 times

Then invokes `/bar/v1/hello-1` 15 times in the same minute.
  - 200 OK - 2 times (`/bar/v1/hello-special` consumed 8 requests but there were only 3 success requests)
  - 429 Too Many Requests - 13 times

The total 200 OK requests for the group **Bar** is 5 even though the defined rate limit is 10 req/min.

### Reason

The reason is we are always incrementing the Redis cache even though the request is over-limited. Enabling the local cache will stop increasing the key `special-policy_3PerMin` (which is actually over-limited) but keep increasing the `group_bar` (this is not over-limited, but the overall status is over-limited).

## Proposal

Introduce a setting in the rate limit service to stop increasing Redis keys when the overall code is over the limit.

```sh
STOP_INCREASING_KEYS_FOR_OVER_LIMIT=true
```
