### ISSUE TITLE
Nested config metrics

### ISSUE THREAD

**Issue by samirmajen** [envoyproxy/ratelimit#418]
Hi, is there a way to update the metrics so they include all parts of a nested configuration and not just the last part? Here's an example:

```domain: test
descriptors:
  - key: path
    value: "/a/b/c"
    descriptors:
      - key: ip-address
        value: "127.0.0.1"
        detailed_metric: true
        rate_limit:
          unit: minute
          requests_per_unit: 5
```

Will emit a metric matching the last part of the nested configuration i.e. the ip-address but does not include the path e.g. the metric it emits is this: "test_ip-address_127.0.0.1_1683105240"

It would be better if the metric was something similar to the following: "test_path_/a/b/c/_ip-address_127.0.0.1_1683105240"

That way its easier to build up a detailed picture of the traffic and update your configuration accordingly. With the current metrics its difficult to limit ip address 127.0.0.1 to 5 requests per minute for path /a/b/c/ and 20 requests per minute for path /d/e/f as the metrics are grouped and you can't easily see that. This will no doubt increase cardinality and should be an opt in (in addition to detailed-metrics)

This should also work for more complex nested configs such as:

```
domain: test
descriptors:
  - key: path
    descriptors:
      - key: ip-address
        descriptors:
          - key: user
            value: "someuser"
            detailed_metric: true
            rate_limit:
              unit: minute
              requests_per_unit: 5
```

should emit: "test_path_/x/y/z/_ip-address_10.10.0.1_user_someuser_1683105240"

Thanks!
