### ISSUE TITLE
Stop incrementing cache keys when overall status is over limited

### ISSUE THREAD

**Issue by chashikajw** [envoyproxy/ratelimit#427]
## Scenario

Let's say we have grouped routes

1. Group: Foo
   -  /foo/v1/hello-1
2. Group: Bar
   - /bar/v1/hello-1
   - /bar/v1/hello-special

And we need to apply the following rate limits for the group: Bar.

1. Per group -> **10** req/min
2. Special rate limit for the route **/bar/v1/hello-special** in group Bar -> **3** req/min

The expectation is,

1. if we invoke **/bar/v1/hello-special** route more than 3 times it should be rate limited.
2. Then the other route(**/bar/v1/hello-1**) has still 7 req/min quota. 
3. Although we invoke **/bar/v1/hello-special** route 5 times,  that should be rate limited from 3 and for the other 2 invocations it should return 429, and **/bar/v1/hello-1** route still should have 7 req/min quota)

But the current behavior is,

1. If we invoke **/bar/v1/hello-special** route 5 times it is rate limited from the 3 requests and for the next 2 invocations, it returns 429 responses. (Overall 5 invocations but only 3 are valid increments)
2. Then if we invoke **/bar/v1/hello-1** route, it should have the 7 req/min quota. But it has only a 5 req/min quota since we invoke **/bar/v1/hello-special** route 5 times including 2 invalid invocations which return 429 responses.

I believe this behavior should be fixed and need to stop incrementing cache keys when the overall status is over-limited.

## Reproducing steps

**Proxy yaml**

```
- match:
    prefix: /foo/v1/hello-1
  route:
    cluster: mock
    rate_limits:
      - actions:
          - generic_key:
              descriptor_key: "group"
              descriptor_value: "foo"


- match:
    prefix: /bar/v1/hello-1
  route:
    cluster: mock
    rate_limits:
      - actions:
          - generic_key:
              descriptor_key: "group"
              descriptor_value: "bar"
- match:
    prefix: /bar/v1/hello-special
  route:
    cluster: mock
    rate_limits:
      - actions:
          - generic_key:
              descriptor_key: "group"
              descriptor_value: "bar"
      - actions:
          - generic_key:
              descriptor_key: "special-policy"
              descriptor_value: "3PerMin"

```

**Rate Limit Service Config Yaml**

```
descriptors:
  - key: group
    rate_limit:
      unit: minute
      requests_per_unit: 10
  - key: special-policy
    value: 3PerMin
    rate_limit:
      unit: minute
      requests_per_unit: 3

```

**Comment by chashikajw** [comment]
Hi @mattklein123,

I will send a pr to fix this issue.

Thank you

**Comment by chashikajw** [comment]
## Proposal

I am planning to introduce the following setting in order to fulfill this requirement.

**STOP_INCREMENTING_CACHE_KEYS_FOR_OVER_LIMIT=true**

If someone enabled the above setting,
  - It will stop incrementing keys from setting the hitsAddend count to 0.

**Comment by sergiosanche** [comment]
Hello,

I have tested the following **descriptors** part with the code associated with the PR 430 and it does not work. Am I doing something wrong?

```
descriptors:
  - key: group
    value: foo
    rate_limit:
      unit: minute
      requests_per_unit: 10

  - key: group
    value: bar
    rate_limit:
      unit: minute
      requests_per_unit: 10
      descriptors:
         - key: special-policy
           value: 3PerMin
           rate_limit:
             unit: minute
             requests_per_unit: 3
```

Regards.
