### ISSUE TITLE
How to define descriptors for multiple domains in configuration?

### ISSUE THREAD

**Issue by nishkarsh-beamery** [envoyproxy/ratelimit#431]
Our Kubernetes cluster has several services running. The ratelimit service is deployed and configured to be used by one of the services. The config file supplied to ratelimit service defines descriptors for one domain (say `service-one`). 

I would like to use the same ratelimit service for a different backend service and hence need to define descriptors for this new service.

I have a `config.yaml` file that is supplied as a `ConfigMap` to ratelimit service. How can I supply descriptors for multiple domains in the file? So far I have tried supplying multiple documents separated by tripple-dash `---` but that doesn't work:

```
domain: service-one
descriptors:
  - key: x-header
    rate_limit:
      unit: second
      requests_per_unit: 20
```

```
domain: service-one
descriptors:
  - key: x-header
    rate_limit:
      unit: second
      requests_per_unit: 20

---
domain: service-two
descriptors:
  - key: y-header
    rate_limit:
      unit: minute
      requests_per_unit: 20
```
