### ISSUE TITLE
Support for prefix match in global filter

### ISSUE THREAD

**Issue by Abhishek627** [envoyproxy/ratelimit#433]
Is there any way to do a prefix match in global filter currently ? I can see prefix match option in local rate limiter but couldn't find anything for global one apart from a "value" match.

**Comment by Abhishek627** [comment]
I see this comment from @mattklein123 https://github.com/envoyproxy/ratelimit/issues/235#issuecomment-797651193. Do we have any workaround since then ?

**Comment by debelopumento** [comment]
@Abhishek627 , I'm looking into the same thing. Did you get your answer when you closed the issue?

**Comment by Abhishek627** [comment]
@debelopumento I tried lots of ways, finally this is working for me.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: prefix-test
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
      proxy:
        proxyVersion: ^1\.13.*
      routeConfiguration:
        vhost:
          name: example.com:443   #Host name which is used in virtual service.
          route:
            name: test-service           # this is the name of http route from virtual service.
    patch:
      operation: MERGE
      value:
        route:
          rate_limits:
          - actions:
            - header_value_match:
                descriptor_value: API_NEW
                headers:
                - name: :path                  
                  prefix_match: /service/auth      
  workloadSelector:
    labels:
      istio: ingressgateway
```

Use this name field in your virtual service : https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRoute and reference it in the filter too .
