### ISSUE TITLE
Problem with nested descriptors

### ISSUE THREAD

**Issue by sergiosanche** [envoyproxy/ratelimit#435]
Hello,

I'm trying the set rate llimit in the following situation:
- CLIENT1 has svc1, svc2, svc3, svc4...svcN.
- CLIENT1 can do 10 req/min.
- CLIENT1 can do 2 req/min to svc1.
- CLIENT1 can do 5 req/min to svc2.
- CLIENT1, svc3, svc4...svcN will have the remaining requests (10 - svc1 - svc2).

For this, I am using the configuration:

```
    domain: productpage-ratelimit
    descriptors:
      - key: CLIENT
        value: "CLIENT1"
        rate_limit:
          unit: minute
          requests_per_unit: 10
        descriptors:
          - key: SVC
            value: svc1
            rate_limit:
              unit: minute
              requests_per_unit: 2
          - key: svc2
            value: ssm
            rate_limit:
              unit: minute
              requests_per_unit: 5
```
```
          rate_limits:
            - actions:
              - request_headers:
                  header_name: "header_client"
                  descriptor_key: "CLIENT"
              - request_headers:
                  header_name: "header_svc"
                  descriptor_key: "SVC"
            - actions: 
              - request_headers:
                  header_name: "header_client"
                  descriptor_key: "CLIENT"
```

The problem I have is that, I can do 8 req/s to svc1 (2 HTTP 200, 6 HTTP 429) but then, if I do 10 requests to svc4 I get 2 HTTP 200 and 8 HTTP 429 when I should get 8 HTTP 200 and 2 HTTP 429.

It looks like all the HTTP 429 answered by svc are counted in svc4.

Why is this happening? How can I avoid this behaviour?

Regards.
