### ISSUE TITLE
Rate Limiting quota adjustment and key identification prior to rate limiting when applying multiple descriptors

### ISSUE THREAD

**Issue by chashikajw** [envoyproxy/ratelimit#440]
This issue is related to issue [1]. We have fixed the main issues from the PR [2], but it is not fully resolved. In order to fully address the increment issue, we should have a way to identify a key is rate limited before it rate limits.

## Scenario

Let's say we have grouped routes

1. Group: Foo
   -  /foo/v1/hello-1
2. Group: Bar
   - /bar/v1/hello-1
   - /bar/v1/hello-special

And we need to apply the following rate limits for the group: Bar.

1. Per group -> **10** req/min
2. Special rate limit for the route **/bar/v1/hello-special** in group Bar -> **3** req/min

The expectation is,

1. if we invoke **/bar/v1/hello-special** route more than 3 times it should be rate limited.
2. Then the other route(**/bar/v1/hello-1**) has  7 req/min quota. 

But the current behaviour is,

1. If we invoke the /bar/v1/hello-special route 6 times, it gets rate-limited after 3 requests. For the next 3 invocations, it returns 429 responses. (In total, there are 6 invocations, but only 3 are considered valid increments.)
2. If we then invoke the /bar/v1/hello-1 route, it should have a 7 req/min quota, but it only has a 6 req/min quota.
3. Similarly, the remaining quota is consistently 1 less than the expected remaining quota.

The issue lies in identifying whether a key is over the limit [3] only after it has been rate-limited, leading to the cessation of key increment. Instead, we need a way to identify this before its rate limited and stopping the key increment in advance.

[1] https://github.com/envoyproxy/ratelimit/issues/427
[2] https://github.com/envoyproxy/ratelimit/pull/430
[3] https://github.com/envoyproxy/ratelimit/blob/main/src/redis/fixed_cache_impl.go#L65

## Reproducing steps

**Proxy yaml**

```
- match:
    prefix: /foo/v1/hello-1
  route:
    cluster: mock
    rate_limits:
      - actions:
          - generic_key:
              descriptor_key: "group"
              descriptor_value: "foo"


- match:
    prefix: /bar/v1/hello-1
  route:
    cluster: mock
    rate_limits:
      - actions:
          - generic_key:
              descriptor_key: "group"
              descriptor_value: "bar"
- match:
    prefix: /bar/v1/hello-special
  route:
    cluster: mock
    rate_limits:
      - actions:
          - generic_key:
              descriptor_key: "group"
              descriptor_value: "bar"
      - actions:
          - generic_key:
              descriptor_key: "special-policy"
              descriptor_value: "3PerMin"

```

**Rate Limit Service Config Yaml**

```
descriptors:
  - key: group
    rate_limit:
      unit: minute
      requests_per_unit: 10
  - key: special-policy
    value: 3PerMin
    rate_limit:
      unit: minute
      requests_per_unit: 3

```
