### ISSUE TITLE
Missing one descriptor value in statsD message with two unspecific value descriptors.

### ISSUE THREAD

**Issue by addf0214** [envoyproxy/ratelimit#442]
I have a rate limit config as follows:
```
    domain: ratelimit
    descriptors:
      - key: method
        detailed_metric: true
        descriptors:
          - key: path
            value: /testRateLimitingApi
            descriptors:
              - key: host
                rate_limit:
                  requests_per_unit: 10
                  unit: minute
                detailed_metric: true
```
There are two keys in this config for which I do not wish to specify any explicit value. The rate limit functionality itself is working as expected and the logs indicate the same:
`
cache key: ratelimit_method_GET_path_/testRateLimitingApi_host_tenant-1.prod.com_1692329460 current: 2
`

However, the message sent to statsD is missing the value for the first descriptor:
`
Creating stats for key: 'ratelimit.method.path_/testRateLimitingApi.host_tenant-1.prod.com'
`

This inconsistency seems like an issue. Can you please confirm if it is indeed an issue or if it's an error on my end?
