### ISSUE TITLE
Applying global ratelimit filter on certain routes only

### ISSUE THREAD

**Issue by haribhatt34** [envoyproxy/ratelimit#460]
Hello everyone. 

I am looking for a way to apply global ratelimit filter for certain routes only. Below is an example of what I trying to achieve.

For a host like "gateway.abc.com"
for prefixes say `/catalog`,` /ratings`, ratelimit filter in HTTP Filter should apply, these request can go to ratelimiter service to check if rate-limit can be applied to them or not.
http://www.gateway.abc.com/catalog - HCM => Ratelimit Filter => ratelimit service => http router filter

for prefixes say `/product`, `/category`, it should skip the ratelimit filter and directly go to the next filter like "http router"
http://www.gateway.abc.com/product -  HCM => http router filter

I know we can achieve similar thing using actions & descriptors, but my intention is not call the ratelimit service at all, when not required.

**Below is what I tried**

```

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit
  namespace: istio-system
spec:
  workloadSelector:
    # select by label in the same namespace
    labels:
      istio: ingressgateway
  configPatches:
    # The Envoy config you want to modify
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        # Adds the Envoy Rate Limit Filter in HTTP filter chain.
        value:
          name: envoy.filters.http.ratelimit
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
            # domain can be anything! Match it to the ratelimter service config
            domain: productpage-ratelimit
            failure_mode_deny: true
            timeout: 10s
            rate_limit_service:
              grpc_service:
                envoy_grpc:
                  cluster_name: outbound|8081||ratelimit.default.svc.cluster.local
                  authority: ratelimit.default.svc.cluster.local
              transport_api_version: V3
            enable_x_ratelimit_headers: 1
            disable_x_envoy_ratelimited_header: true
            
    - applyTo: ROUTE_CONFIGURATION
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            name: "*" # Matches all virtual hosts
      patch:
        operation: MERGE
        value:
          virtual_hosts:
            - name: "*" # Matches all virtual hosts
              routes:
                - match:
                    prefix: "/catalog" # Specify your route here
                  typed_per_filter_config:
                    envoy.filters.http.ratelimit:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimitPerRoute
                      rate_limits:
                        - actions: # Define your rate limit criteria here
                            - request_headers:
                                header_name: ":path"
                                descriptor_key: "path"
                - match:
                    prefix: "/ratings" # Specify another route here
                  typed_per_filter_config:
                    envoy.filters.http.ratelimit:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimitPerRoute
                      rate_limits:
                        - actions:
                            - request_headers:
                                header_name: ":path"
                                descriptor_key: "path" 
```

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ratelimit-actions
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            route:
              action: ANY
      patch:
        operation: MERGE
        value:
          rate_limits:
            # Action 1
            - actions:
                # Match on path prefix "/productpage" 
                - header_value_match:
                    descriptor_value: productpath
                    headers:
                      - name: :path
                        prefix_match: /productpage
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: productpage-ratelimit
    descriptors:
      - key: header_match 
        value: productpath
        rate_limit:
          unit: minute
          requests_per_unit: 2
```
```
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
  - name: redis
    port: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:alpine
        imagePullPolicy: Always
        name: redis
        ports:
        - name: redis
          containerPort: 6379
      restartPolicy: Always
      serviceAccountName: ""
---
apiVersion: v1
kind: Service
metadata:
  name: ratelimit
  labels:
    app: ratelimit
spec:
  ports:
  - name: http-port
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: grpc-port
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: http-debug
    port: 6070
    targetPort: 6070
    protocol: TCP
  selector:
    app: ratelimit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratelimit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratelimit
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ratelimit
    spec:
      containers:
      - image: envoyproxy/ratelimit:9d8d70a8 # 2022/08/16
        imagePullPolicy: Always
        name: ratelimit
        command: ["/bin/ratelimit"]
        env:
        - name: LOG_LEVEL
          value: debug
        - name: REDIS_SOCKET_TYPE
          value: tcp
        - name: REDIS_URL
          value: redis:6379
        - name: USE_STATSD
          value: "false"
        - name: RUNTIME_ROOT
          value: /data
        - name: RUNTIME_SUBDIRECTORY
          value: ratelimit
        - name: RUNTIME_WATCH_ROOT
          value: "false"
        - name: RUNTIME_IGNOREDOTFILES
          value: "true"
        - name: HOST
          value: "::"
        - name: GRPC_HOST
          value: "::"
        ports:
        - containerPort: 8080
        - containerPort: 8081
        - containerPort: 6070
        volumeMounts:
        - name: config-volume
          mountPath: /data/ratelimit/config
      volumes:
      - name: config-volume
        configMap:
          name: ratelimit-config
```
