### ISSUE TITLE
Name attribute for rate limits are not returned

### ISSUE THREAD

**Issue by jespersoderlund** [envoyproxy/ratelimit#593]
The rate limit quota policy have an optional name attribute that is not being returned to envoy.

With the config like:
```
domain: a_domain
descriptors:
  - key: operation_type
     rate_limit:
         unit: second
         requests_per_unit: 10
         name: ops_limit
```
The returned header will be:
`X-Ratelimit-Limit: 10, 10;w=1`

Looking at the GRPC spec and envoy source code, the header should be:
`X-Ratelimit-Limit: 10, 10;w=1;name="ops_limit"`

Looking at the code in the ratelimit service there is a point where the *name* attribute is not copied correctly in the GRPC response.

I will submit a patch to fix the issue
