### ISSUE TITLE
[Feature request] rate limit expiration 

### ISSUE THREAD

**Issue by yusofg2** [envoyproxy/ratelimit#800]
Use-case: Some rate limits are needed for a relatively short period of time (e.g. under an incident). If ratelimits had an expiry time, the service operator does not need to manually remove the limits that are no longer needed or relevant.

Rationale: The ratelimit service configuration and logic does not accommodate rate limit expiry timestamps. To implement rule expiry, an external control plane needs to remove the rate limits when they expire and update the ratelimit service configuration. If the service handled ratelimit expiry, similar to many ruleset engines, it would be more self-contained.

Possible config example shown in the **last line below** (adapted from [here](https://github.com/envoyproxy/ratelimit/blob/6a2e8262874f012d08830cc34ba8058e66a33819/examples/ratelimit/config/example.yaml#L40-L54)):
```
  - key: foo
    rate_limit:
      unit: minute
      requests_per_unit: 2
    descriptors:
      - key: bar
        rate_limit:
          unit: minute
          requests_per_unit: 3
      - key: bar
        value: bkthomps
        rate_limit:
          name: bkthomps
          unit: minute
          requests_per_unit: 1
          expiry: 2025-01-01 12:00:00
```
